---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  # See https://github.com/ansible-community/ansible-lint/issues/1329
  # Exclude molecule/default/ because of this issue
  ansible-lint --exclude=molecule/default/
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    capabilities:
      - SYS_ADMIN
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible