---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 4"
defaults:
  run:
    working-directory: 'molecule_example'
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: centos8
            playbook: converge.yml
          - distro: ubi8
            playbook: converge.yml
          - distro: centos7
            playbook: converge.yml
          - distro: ubuntu2004
            playbook: converge.yml
          - distro: ubuntu1804
            playbook: converge.yml
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'molecule_example'
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies
        run: pip install --no-cache-dir --upgrade --requirement ./python_requirements.txt
      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}